import htmlPlugin from 'eslint-plugin-html';

export default [
  {
    ignores: ['node_modules/**', '*.min.js', '**/*.pdf', '**/*.png', '**/*.jpg', 'eslint.config.js'],
  },
  {
    files: ['**/*.html'],
    plugins: { html: htmlPlugin },
  },
  {
    files: ['**/*.js', '**/*.html'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'script',
      globals: {
        hljs: 'readonly',
        IntersectionObserver: 'readonly',
        localStorage: 'readonly',
        document: 'readonly',
        window: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        fetch: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        history: 'readonly',
        innerWidth: 'readonly',
        innerHeight: 'readonly',
        onresize: 'writable',
        alert: 'readonly',
        Math: 'readonly',
        Date: 'readonly',
        JSON: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        Image: 'readonly',
        Audio: 'readonly',
        URL: 'readonly',
        Blob: 'readonly',
        FileReader: 'readonly',
        FormData: 'readonly',
        XMLHttpRequest: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        MouseEvent: 'readonly',
        KeyboardEvent: 'readonly',
        Error: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        Promise: 'readonly',
        Proxy: 'readonly',
        Reflect: 'readonly',
        Symbol: 'readonly',
        WeakMap: 'readonly',
        WeakSet: 'readonly',
        Intl: 'readonly',
        ArrayBuffer: 'readonly',
        Uint8Array: 'readonly',
        TextDecoder: 'readonly',
        TextEncoder: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        self: 'readonly',
        top: 'readonly',
        parent: 'readonly',
        frames: 'readonly',
        scrollTo: 'readonly',
        getComputedStyle: 'readonly',
        matchMedia: 'readonly',
        addEventListener: 'readonly',
        removeEventListener: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': 'warn',
      'no-undef': 'warn',
      'no-console': 'off',
      'no-debugger': 'warn',
      eqeqeq: ['warn', 'always'],
      curly: ['warn', 'multi-or-nest'],
      'no-var': 'warn',
      'prefer-const': 'warn',
      'no-multiple-empty-lines': ['warn', { max: 2 }],
      'no-trailing-spaces': 'warn',
      semi: ['warn', 'always'],
      quotes: ['off'],
    },
  },
];
